# Linear Regression vs. LASSO

### Titanic Age Prediction

In [8]:
alpha = 100

import matplotlib.pyplot as plt
import numpy as np 
import pandas as pd
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import r2_score

import pandas as pd
import numpy as np
np.random.seed(12356)
df = pd.read_csv('titanic.csv')

df = df[df['Age'].notna()]

# Assign input variables
X = df.loc[:,['Fare','SibSp','Parch']]

# Assign target variable
y = df['Age']

X = pd.get_dummies(X)
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

model = LinearRegression()
model.fit(x_train, y_train)

coef1 = pd.DataFrame({'Variable':x_train.columns, 
                     'Coef':model.coef_,
                      'Model': 'Linear',
                      'Data': 'Original'
                    })

lm_org = r2_score(y_test, model.predict(x_test))
model = linear_model.Lasso(alpha=alpha)
model.fit(x_train, y_train)

coef2 = pd.DataFrame({'Variable':x_train.columns, 
                     'Coef':model.coef_,
                      'Model':'LASSO',
                      'Data': 'Original'
                    })

lasso_org = r2_score(y_test, model.predict(x_test))
coef = pd.concat([coef1, coef2], ignore_index=True, axis=1)
coef = coef.drop([2, 3, 4, 6, 7], axis=1)
coef.columns = ['Variable','Linear Model', 'LASSO']
coef.round(3)

  Variable  Linear Model  LASSO
0     Fare         0.047    0.0
1    SibSp        -4.356   -0.0
2    Parch        -2.395   -0.0

### Boston House Price Prediction

In [14]:
alpha=0.5

from sklearn.datasets import load_boston
boston=load_boston()
boston_df=pd.DataFrame(boston.data,columns=boston.feature_names)
#print boston_df.info()
# add another column that contains the house prices which in scikit learn datasets are considered as target
boston_df['Price']=boston.target
#print boston_df.head(3)
newX=boston_df.drop('Price',axis=1)
newY=boston_df['Price']
#print type(newY)# pandas core frame
x_train,x_test,y_train,y_test=train_test_split(newX,newY,test_size=0.9,random_state=27)

newX=boston_df.drop('Price',axis=1)
newY=boston_df['Price']

#print type(newY)# pandas core frame
x_train,x_test,y_train,y_test=train_test_split(newX,newY,test_size=0.9,random_state=27)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

model = LinearRegression()
model.fit(x_train, y_train)

coef1 = pd.DataFrame({'Variable':x_train.columns, 
                     'Coef':model.coef_,
                      'Model': 'Linear',
                      'Data': 'Original'
                    })

lm_org = r2_score(y_test, model.predict(x_test))
model = linear_model.Lasso(alpha=alpha)
model.fit(x_train, y_train)

coef2 = pd.DataFrame({'Variable':x_train.columns, 
                     'Coef':model.coef_,
                      'Model':'LASSO',
                      'Data': 'Original'
                    })

lasso_org = r2_score(y_test, model.predict(x_test))
coef = pd.concat([coef1, coef2], ignore_index=True, axis=1)
coef = coef.drop([2, 3, 4, 6, 7], axis=1)
coef.columns = ['Variable','Linear Model', 'LASSO']
coef.round(3)

   Variable  Linear Model  LASSO
0      CRIM         0.651  0.234
1        ZN         0.061  0.069
2     INDUS        -0.077 -0.019
3      CHAS        12.473  0.000
4       NOX       -11.575 -0.000
5        RM         8.523  6.209
6       AGE        -0.055 -0.020
7       DIS        -1.721 -1.120
8       RAD        -0.240  0.123
9       TAX         0.003 -0.007
10  PTRATIO         0.066 -0.179
11        B         0.037  0.039
12    LSTAT        -0.226 -0.333

In [3]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**

    :Number of Instances: 506

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
        - B        1000(Bk - 0.63)^2 where Bk is the proportion of black people by town
        - LSTAT    % lower status of the population
        - MEDV     Median value of owner-occupied homes in $1000's

    :Missing Attribute Values: None

    :Creator: Harrison, D. and Rubinfeld, D.L.

This is a copy of UCI ML housing dataset.
https://archive.ics.uci.edu/ml/machine-learning-databases/housing/


This dataset was taken from the StatLib library which is maintained at Carnegie Mellon University.

The Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic
prices and the demand for clean air', J. Environ. Economics & Management,
vol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics
...', Wiley, 1980.   N.B. Various transformations are used in the table on
pages 244-261 of the latter.

The Boston house-price data has been used in many machine learning papers that address regression
problems.

.. topic:: References

   - Belsley, Kuh & Welsch, 'Regression diagnostics: Identifying Influential Data and Sources of Collinearity', Wiley, 1980. 244-261.
   - Quinlan,R. (1993). Combining Instance-Based and Model-Based Learning. In Proceedings on the Tenth International Conference of Machine Learning, 236-243, University of Massachusetts, Amherst. Morgan Kaufmann.